baseurl = "https://rodolfovalentim.github.io/"
title = "Portfolio's Rodolfo Valentim"
googleAnalytics = "UA-78770190-1"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Rodolfo Valentim"
    description = "Rodolfo's personal website"
    keywords = "blog,developer,personal"
    info = "Computer Engineer and Developer "
    avatarurl = "images/avatar.jpg"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

[taxonomies]
  series = "series"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/rodolfovalentim/"

[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"

        [[languages.en.menu.main]]
        name = "Research"
        weight = 4
        url = "/research/"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 5
        url = "/contact/"


    [languages.pt-br]
        languagename = "Português"
        title = "Portifólio Rodolfo Valentim"

        [languages.pt-br.params]
            author = "Rodolfo Valentim"
            info = "Engenheiro de Computação e Desenvolvedor"
            description = "Portifólio de Rodolfo Valentim"
            keywords = "blog,desenvolvedor,pessoal"
            footercontent = ""

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Sobre"
            weight = 1
            url = "/pt-br/about/"

            [[languages.pt-br.menu.main]]
            name = "Blog"
            weight = 2
            url = "/pt-br/posts/"

            [[languages.pt-br.menu.main]]
            name = "Projetos"
            weight = 3
            url = "/pt-br/projects/"

            [[languages.pt-br.menu.main]]
            name = "Pesquisa"
            weight = 4
            url = "/pt-br/research/"

            [[languages.pt-br.menu.main]]
            name = "Contato"
            weight = 5
            url = "/pt-br/contact/"
